[#33363#csoip] Suppression du script de pre-installation qui empeche de preinstaller un paquetage sur PC avant transfert sur la cible

diff --git a/debian/pkg_knld.postinst b/debian/pkg_knld.postinst
--- a/debian/pkg_knld.postinst
+++ b/debian/pkg_knld.postinst
@@ -1,6 +1,20 @@
 #!/bin/sh
 export PATH=$PATH:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
 
+echo "Verifying model..."
+verified=false
+model=`cat /proc/device-tree/model`
+for list in KNL_MODEL_SUPPORT ; do
+	if [ "${list}" == "${model}" ]; then
+		verified=true
+	fi
+done
+if [ "${verified}" == "false" ]; then
+	echo "Error: This package is only for KNL_MODEL_SUPPORT model board"
+	exit 1
+fi
+echo "LINUX_FILE_NAME installing..."
+
 # copy dtb file
 dd if=/dev/mtd2 bs=`cat /tmp/root/dtb.bin | wc -c` count=1 2>/dev/null | cmp /tmp/root/dtb.bin 2>/dev/null
 if [ $? -eq 0 ]
